### ISSUE TITLE
What is the format of tfrecords and properties.json?

### ISSUE THREAD

**Issue by zobunnie** [biomatterdesigns/ProteinGAN#1]
I have a fasta file of peptides. 
How do I convert it into train/{1}_{2}_{3}.tfrecords?
Could you provide the file of tfrecord and the input data of tfrecord?
Also, what is the format of properties.json?
Thank you!

**Comment by donatasrep** [comment]
Zobunnie,

You can use the save_as_tfrecords_multithreaded method from common.preprocessing to create TFRecords. You need to create pandas dataframe with all required data such as sequences, labels and upsampling factors which will be added as part of the file name. 

Please note: you need to have training and validation files as well as take care of balancing that are controlled by {2}, {3} - in the file name. 

For a successful execution you would also need blast databases which you have to create using makeblastdb tool.

If you have any additional questions, please reach out to support@biomatterdesigns.com and we will be glad to help.
